// GENERATED by scripts/gen-abi.mjs — DO NOT EDIT BY HAND.
// Provenance: forge artifact out/PactRegistry.sol/PactRegistry.json (.abi).
// Regenerate: pnpm --filter @pact-network/protocol-evm-v1-client gen:abi
// Drift guard (D-A, captain GATE-A CONDITION): pnpm --filter @pact-network/protocol-evm-v1-client check:abi
export const PactRegistryAbi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "bool",
        "name": "paused",
        "type": "bool"
      }
    ],
    "name": "ProtocolPaused",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes16",
        "name": "callId",
        "type": "bytes16"
      },
      {
        "indexed": true,
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "agent",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "premium",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "refund",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "actualRefund",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "uint8",
        "name": "status",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "breach",
        "type": "bool"
      },
      {
        "indexed": false,
        "internalType": "uint32",
        "name": "latencyMs",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "timestamp",
        "type": "uint64"
      }
    ],
    "name": "CallSettled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "paused",
        "type": "bool"
      }
    ],
    "name": "EndpointPaused",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "funder",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "amount",
        "type": "uint64"
      }
    ],
    "name": "PoolToppedUp",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      }
    ],
    "name": "EndpointConfigUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      }
    ],
    "name": "EndpointRegistered",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      }
    ],
    "name": "FeeRecipientsUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "sender",
        "type": "address"
      }
    ],
    "name": "RoleGranted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "sender",
        "type": "address"
      }
    ],
    "name": "RoleRevoked",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "previousAdminRole",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "newAdminRole",
        "type": "bytes32"
      }
    ],
    "name": "RoleAdminChanged",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "AccessControlBadConfirmation",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ArithmeticOverflow",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "DEFAULT_ADMIN_ROLE",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "EndpointAlreadyRegistered",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EndpointNotFound",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "FeeBpsExceedsCap",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "FeeBpsSumOver10k",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "FeeRecipientArrayTooLong",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "FeeRecipientDuplicateDestination",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidAffiliateAta",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidFeeRecipientKind",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidSlug",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MissingTreasuryEntry",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MultipleTreasuryRecipients",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SETTLER_ROLE",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "TreasuryBpsZero",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UnauthorizedAuthority",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "authority",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "maxTotalFeeBps",
    "outputs": [
      {
        "internalType": "uint16",
        "name": "",
        "type": "uint16"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "protocolPaused",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "treasuryVault",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "usdc",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "neededRole",
        "type": "bytes32"
      }
    ],
    "name": "AccessControlUnauthorizedAccount",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "authority_",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "usdc_",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "treasuryVault_",
        "type": "address"
      },
      {
        "internalType": "uint16",
        "name": "maxTotalFeeBps_",
        "type": "uint16"
      },
      {
        "components": [
          {
            "internalType": "uint8",
            "name": "kind",
            "type": "uint8"
          },
          {
            "internalType": "address",
            "name": "destination",
            "type": "address"
          },
          {
            "internalType": "uint16",
            "name": "bps",
            "type": "uint16"
          }
        ],
        "internalType": "struct IPactRegistry.FeeRecipient[8]",
        "name": "defaultRecipients_",
        "type": "tuple[8]"
      },
      {
        "internalType": "uint8",
        "name": "defaultCount_",
        "type": "uint8"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [
      {
        "internalType": "bool",
        "name": "paused",
        "type": "bool"
      }
    ],
    "name": "pauseProtocol",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      },
      {
        "components": [
          {
            "internalType": "uint8",
            "name": "kind",
            "type": "uint8"
          },
          {
            "internalType": "address",
            "name": "destination",
            "type": "address"
          },
          {
            "internalType": "uint16",
            "name": "bps",
            "type": "uint16"
          }
        ],
        "internalType": "struct IPactRegistry.FeeRecipient[8]",
        "name": "recipients",
        "type": "tuple[8]"
      },
      {
        "internalType": "uint8",
        "name": "count",
        "type": "uint8"
      }
    ],
    "name": "updateFeeRecipients",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      },
      {
        "internalType": "bool",
        "name": "paused",
        "type": "bool"
      }
    ],
    "name": "pauseEndpoint",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      },
      {
        "internalType": "uint64",
        "name": "actualRefund",
        "type": "uint64"
      }
    ],
    "name": "recordRefundPaid",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      },
      {
        "internalType": "uint64",
        "name": "flatPremium",
        "type": "uint64"
      },
      {
        "internalType": "uint16",
        "name": "percentBps",
        "type": "uint16"
      },
      {
        "internalType": "uint32",
        "name": "slaLatencyMs",
        "type": "uint32"
      },
      {
        "internalType": "uint64",
        "name": "imputedCost",
        "type": "uint64"
      },
      {
        "internalType": "uint64",
        "name": "exposureCapPerHour",
        "type": "uint64"
      },
      {
        "internalType": "bool",
        "name": "feeRecipientsPresent",
        "type": "bool"
      },
      {
        "internalType": "uint8",
        "name": "feeRecipientCount",
        "type": "uint8"
      },
      {
        "components": [
          {
            "internalType": "uint8",
            "name": "kind",
            "type": "uint8"
          },
          {
            "internalType": "address",
            "name": "destination",
            "type": "address"
          },
          {
            "internalType": "uint16",
            "name": "bps",
            "type": "uint16"
          }
        ],
        "internalType": "struct IPactRegistry.FeeRecipient[8]",
        "name": "feeRecipients",
        "type": "tuple[8]"
      }
    ],
    "name": "registerEndpoint",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      },
      {
        "internalType": "uint64",
        "name": "flatPremium",
        "type": "uint64"
      },
      {
        "internalType": "uint16",
        "name": "percentBps",
        "type": "uint16"
      },
      {
        "internalType": "uint32",
        "name": "slaLatencyMs",
        "type": "uint32"
      },
      {
        "internalType": "uint64",
        "name": "imputedCost",
        "type": "uint64"
      },
      {
        "internalType": "uint64",
        "name": "exposureCapPerHour",
        "type": "uint64"
      }
    ],
    "name": "updateEndpointConfig",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      },
      {
        "internalType": "uint64",
        "name": "premium",
        "type": "uint64"
      },
      {
        "internalType": "bool",
        "name": "breach",
        "type": "bool"
      },
      {
        "internalType": "uint64",
        "name": "intendedRefund",
        "type": "uint64"
      }
    ],
    "name": "recordCallAndCapAccrual",
    "outputs": [
      {
        "internalType": "uint64",
        "name": "payableRefund",
        "type": "uint64"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      }
    ],
    "name": "getEndpoint",
    "outputs": [
      {
        "components": [
          {
            "internalType": "bool",
            "name": "paused",
            "type": "bool"
          },
          {
            "internalType": "uint64",
            "name": "flatPremium",
            "type": "uint64"
          },
          {
            "internalType": "uint16",
            "name": "percentBps",
            "type": "uint16"
          },
          {
            "internalType": "uint32",
            "name": "slaLatencyMs",
            "type": "uint32"
          },
          {
            "internalType": "uint64",
            "name": "imputedCost",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "exposureCapPerHour",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "totalCalls",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "totalBreaches",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "totalPremiums",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "totalRefunds",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "currentPeriodStart",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "currentPeriodRefunds",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "lastUpdated",
            "type": "uint64"
          },
          {
            "internalType": "uint8",
            "name": "feeRecipientCount",
            "type": "uint8"
          },
          {
            "components": [
              {
                "internalType": "uint8",
                "name": "kind",
                "type": "uint8"
              },
              {
                "internalType": "address",
                "name": "destination",
                "type": "address"
              },
              {
                "internalType": "uint16",
                "name": "bps",
                "type": "uint16"
              }
            ],
            "internalType": "struct IPactRegistry.FeeRecipient[8]",
            "name": "feeRecipients",
            "type": "tuple[8]"
          }
        ],
        "internalType": "struct IPactRegistry.EndpointConfig",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      }
    ],
    "name": "isRegistered",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "grantRole",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "hasRole",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "revokeRole",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "callerConfirmation",
        "type": "address"
      }
    ],
    "name": "renounceRole",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      }
    ],
    "name": "getRoleAdmin",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "interfaceId",
        "type": "bytes4"
      }
    ],
    "name": "supportsInterface",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
