// GENERATED by scripts/gen-abi.mjs — DO NOT EDIT BY HAND.
// Provenance: parsed from src/errors/PactErrors.sol (locked source).
// Regenerate: pnpm --filter @pact-network/protocol-evm-v1-client gen:abi
// Drift guard (D-A, captain GATE-A CONDITION): pnpm --filter @pact-network/protocol-evm-v1-client check:abi
export const PactErrorsAbi = [
  {
    "inputs": [],
    "name": "ArithmeticOverflow",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "BatchTooLarge",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "DuplicateCallId",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EndpointAlreadyRegistered",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EndpointNotFound",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EndpointPaused",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ExposureCapExceeded",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "FeeBpsExceedsCap",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "FeeBpsSumOver10k",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "FeeRecipientArrayTooLong",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "FeeRecipientDuplicateDestination",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "FeeRecipientInvalidUsdcMint",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InsufficientBalance",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidAffiliateAta",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidFeeRecipientKind",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidProtocolConfig",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidSlug",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidTimestamp",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidTreasury",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MissingTreasuryEntry",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MultipleTreasuryRecipients",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PoolDepleted",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PremiumTooSmall",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ProtocolConfigNotInitialized",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ProtocolPaused",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "RecipientCoverageMismatch",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TreasuryBpsZero",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TreasuryNotInitialized",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UnauthorizedAuthority",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UnauthorizedSettler",
    "type": "error"
  }
] as const;
