// GENERATED by scripts/gen-abi.mjs — DO NOT EDIT BY HAND.
// Provenance: forge artifact out/PactEvents.sol/PactEvents.json (.abi).
// Regenerate: pnpm --filter @pact-network/protocol-evm-v1-client gen:abi
// Drift guard (D-A, captain GATE-A CONDITION): pnpm --filter @pact-network/protocol-evm-v1-client check:abi
export const PactEventsAbi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "bool",
        "name": "paused",
        "type": "bool"
      }
    ],
    "name": "ProtocolPaused",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes16",
        "name": "callId",
        "type": "bytes16"
      },
      {
        "indexed": true,
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "agent",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "premium",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "refund",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "actualRefund",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "uint8",
        "name": "status",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "breach",
        "type": "bool"
      },
      {
        "indexed": false,
        "internalType": "uint32",
        "name": "latencyMs",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "timestamp",
        "type": "uint64"
      }
    ],
    "name": "CallSettled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "paused",
        "type": "bool"
      }
    ],
    "name": "EndpointPaused",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "funder",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "amount",
        "type": "uint64"
      }
    ],
    "name": "PoolToppedUp",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      }
    ],
    "name": "EndpointConfigUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      }
    ],
    "name": "EndpointRegistered",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes16",
        "name": "slug",
        "type": "bytes16"
      }
    ],
    "name": "FeeRecipientsUpdated",
    "type": "event"
  }
] as const;
