// Shared ABI extraction + canonicalization for the WP-EVM-06 D-A ABI sourcing
// guard. The committed src/abi/*.ts modules MUST stay in sync with the LOCKED
// forge-compiled contracts — never merely self-consistent (captain GATE-A
// CONDITION on D-A). gen-abi.mjs writes the committed modules; the captain's
// drift guard (check-abi-drift.mjs) regenerates from a fresh `forge build` +
// the locked PactErrors.sol source and diffs, failing loudly on any drift.
//
// Provenance split (intentional, recorded for the WP-06 parity matrix):
//  - PactRegistry/PactPool/PactSettler/PactEvents: forge artifact `.abi`
//    (out/<C>.sol/<C>.json) — the actual compiled contract surface.
//  - PactErrors: parsed from src/errors/PactErrors.sol — error.rs's 30-variant
//    mirror is free-standing `error X();` declarations with no forge artifact;
//    Solidity contract ABIs only carry the errors each contract can revert
//    (the §4-unreachable variants are intentionally absent from compiled ABIs
//    but MUST exist in the client error map for parity). The source file IS a
//    locked contract source at HEAD, so this is still locked-derived.

import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
export const CONTRACTS_DIR = resolve(here, "../../program-evm/protocol-evm-v1");
export const ABI_OUT_DIR = resolve(here, "../src/abi");

// Forge-artifact-sourced ABIs (contractName === artifact basename).
export const FORGE_ABIS = ["PactRegistry", "PactPool", "PactSettler", "PactEvents"];
// Source-parsed ABI (free-standing custom errors, no forge artifact).
export const SOURCE_ABIS = ["PactErrors"];
export const ALL_ABIS = [...FORGE_ABIS, ...SOURCE_ABIS];

const PACT_ERRORS_SOL = resolve(CONTRACTS_DIR, "src/errors/PactErrors.sol");

/** Recursively sort object keys so serialization is order-independent. */
function sortDeep(value) {
  if (Array.isArray(value)) return value.map(sortDeep);
  if (value && typeof value === "object") {
    const out = {};
    for (const k of Object.keys(value).sort()) out[k] = sortDeep(value[k]);
    return out;
  }
  return value;
}

/**
 * Canonicalize an ABI array: drop docs/metadata noise, deep-sort each item's
 * keys, then sort the array by the canonical JSON of each item. Deterministic
 * regardless of compiler emission order — so gen and drift produce identical
 * bytes for an unchanged locked contract set.
 */
export function canonicalizeAbi(abi) {
  const items = abi.map(sortDeep);
  items.sort((a, b) => (JSON.stringify(a) < JSON.stringify(b) ? -1 : 1));
  return items;
}

/** Extract a forge artifact's ABI from the contracts package's out/ dir. */
export function extractForgeAbi(contractName) {
  const p = resolve(CONTRACTS_DIR, "out", `${contractName}.sol`, `${contractName}.json`);
  if (!existsSync(p)) {
    throw new Error(
      `forge artifact missing: ${p}\nRun \`forge build\` in ${CONTRACTS_DIR} first.`,
    );
  }
  const artifact = JSON.parse(readFileSync(p, "utf8"));
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`forge artifact has no .abi array: ${p}`);
  }
  return canonicalizeAbi(artifact.abi);
}

/**
 * Parse src/errors/PactErrors.sol into a synthetic error ABI. error.rs's 30
 * PactError variants are mirrored 1:1 as zero-argument `error Name();`
 * declarations (design spec §3 binding rule). The source file is the named
 * authority (handoff §(b) ruling 1) — error.rs has 30; FeeBpsSumOver10k(6018)
 * is the 30th and IS present in PactErrors.sol.
 */
export function extractPactErrorsAbi() {
  if (!existsSync(PACT_ERRORS_SOL)) {
    throw new Error(`locked source missing: ${PACT_ERRORS_SOL}`);
  }
  const src = readFileSync(PACT_ERRORS_SOL, "utf8");
  const names = [];
  const re = /^\s*error\s+([A-Za-z_]\w*)\s*\(\s*\)\s*;/gm;
  let m;
  while ((m = re.exec(src)) !== null) names.push(m[1]);
  if (names.length === 0) {
    throw new Error(`parsed 0 errors from ${PACT_ERRORS_SOL} — parser/source drift`);
  }
  if (new Set(names).size !== names.length) {
    throw new Error(`duplicate error name parsed from ${PACT_ERRORS_SOL}`);
  }
  const abi = names.map((name) => ({ type: "error", name, inputs: [] }));
  return canonicalizeAbi(abi);
}

/** Build the full {name -> canonical abi} map from the LOCKED contract set. */
export function buildAbiMap() {
  const map = {};
  for (const c of FORGE_ABIS) map[c] = extractForgeAbi(c);
  map.PactErrors = extractPactErrorsAbi();
  return map;
}

/** Render a committed src/abi/<Name>.ts module (viem `as const`). */
export function renderAbiModule(name, abi) {
  const provenance = FORGE_ABIS.includes(name)
    ? `forge artifact out/${name}.sol/${name}.json (.abi)`
    : `parsed from src/errors/${name}.sol (locked source)`;
  return (
    `// GENERATED by scripts/gen-abi.mjs — DO NOT EDIT BY HAND.\n` +
    `// Provenance: ${provenance}.\n` +
    `// Regenerate: pnpm --filter @pact-network/protocol-evm-v1-client gen:abi\n` +
    `// Drift guard (D-A, captain GATE-A CONDITION): pnpm --filter ` +
    `@pact-network/protocol-evm-v1-client check:abi\n` +
    `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`
  );
}

/** Read back the abi array embedded in a committed src/abi/<Name>.ts module. */
export function readCommittedAbi(name) {
  const p = resolve(ABI_OUT_DIR, `${name}.ts`);
  if (!existsSync(p)) throw new Error(`committed ABI module missing: ${p}`);
  const txt = readFileSync(p, "utf8");
  const m = txt.match(/export const \w+Abi = ([\s\S]*?) as const;\s*$/);
  if (!m) throw new Error(`could not parse committed ABI module: ${p}`);
  return JSON.parse(m[1]);
}
