name = "pact-proxy"
main = "src/index.ts"
compatibility_date = "2026-04-01"
compatibility_flags = ["nodejs_compat"]

[vars]
PACT_VERSION = "v1"

[[kv_namespaces]]
binding = "PACT_KV"
id = "<set-on-create>"

[observability]
enabled = true

# TODO: confirm zone with Rick
[routes]
pattern = "market.pactnetwork.io/*"
zone_name = "pactnetwork.io"
